name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0/30 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: run: go run cmd/blueheeler/once/main.go -s ${{ secrets.server }} -u ${{ secrets.username }} -p ${{ secrets.password }}
